/**
 * Phase 8A: Analytics Truth & Data Lineage Contract
 * 
 * Strict data contract ensuring every displayed statistic has a traceable provenance,
 * confidence score, calculation timestamp, and explicit state (never false zeroes).
 */

export type MetricStatus =
  | 'AVAILABLE'
  | 'INSUFFICIENT_DATA'
  | 'ERROR'
  | 'CALCULATING'
  | 'UNAVAILABLE';

export type MetricSource =
  | 'ACTUAL'         // Direct ledger transaction, verified provider data, or physical meter reading
  | 'PROVIDER'       // Authoritative data directly returned by DISCO/utility gateway
  | 'METER_READING'  // Physical meter reading
  | 'DERIVED'        // Deterministically computed from verified ledger transactions
  | 'DATABASE'       // Direct authoritative database query
  | 'ESTIMATED'      // Statistical approximation or self-reported appliance survey with clear disclaimer
  | 'FORECAST'       // Grounded mathematical projection derived from historical cadence
  | 'AI'             // Generated by AI assistant
  | 'UNAVAILABLE';   // Data does not exist; metric must not display a fabricated number

export type MetricConfidence = 'HIGH' | 'MEDIUM' | 'LOW' | null;

export interface AnalyticsValue<T> {
  value: T | null;
  status: MetricStatus;
  source: MetricSource;
  confidence: MetricConfidence;
  calculatedAt: string | null;
  errorMessage?: string | null;
}

export interface PeriodChartBucket {
  label: string;
  fullLabel: string;
  count: number;
  amountNaira: number;
  unitsKwh: number | null;
}

export interface PeriodChartData {
  period: '7d' | '30d' | '90d' | '1y';
  buckets: PeriodChartBucket[];
  totalSpendNaira: number;
  totalPurchases: number;
  totalUnitsKwh: number | null;
  hasData: boolean;
  status: MetricStatus;
}
