import { EnergyContext, StructuredAIResponse, StructuredInsightsAnalytics } from '@/types/ai';
import { AI_CONFIG } from './ai-config';

export interface GuardrailValidationResult {
  isValid: boolean;
  sanitizedResponse?: StructuredAIResponse;
  rejectionReason?: string;
}

export interface AnalyticsValidationResult {
  isValid: boolean;
  sanitizedAnalytics?: StructuredInsightsAnalytics;
  rejectionReason?: string;
}

export class AIGuardrails {
  private static readonly RATE_LIMIT_PER_MINUTE = AI_CONFIG.guardrails.rateLimitPerMinute;
  private static readonly RATE_LIMIT_PER_DAY = AI_CONFIG.guardrails.rateLimitPerDay;
  private static readonly rateLimitMap = new Map<string, { minuteCount: number; minuteWindow: number; dayCount: number; dayWindow: number }>();
  private static readonly responseCache = new Map<string, { response: StructuredAIResponse; expiresAt: number }>();
  private static readonly analyticsCache = new Map<string, { analytics: StructuredInsightsAnalytics; expiresAt: number }>();

  /**
   * Evaluates user query for prompt injection and security threats.
   */
  static sanitizeAndValidateQuery(query: string): { isSafe: boolean; sanitizedQuery: string; reason?: string } {
    if (!query || query.trim().length === 0) {
      return { isSafe: false, sanitizedQuery: '', reason: 'Empty query.' };
    }

    const trimmed = query.trim().slice(0, 500); // Limit maximum query length
    const lower = trimmed.toLowerCase();

    // Block prompt injection patterns
    const injectionPatterns = [
      'ignore previous instructions',
      'ignore all instructions',
      'system prompt',
      'reveal secrets',
      'reveal api key',
      'show api key',
      'database schema',
      'drop table',
      'select * from',
      'execute sql',
      'delete from',
      'pretend you are',
      'jailbreak',
      'give me another user',
      'other users data',
      'bypass meter',
    ];

    for (const pattern of injectionPatterns) {
      if (lower.includes(pattern)) {
        return {
          isSafe: false,
          sanitizedQuery: trimmed,
          reason: 'Query contains disallowed keywords or injection instructions.',
        };
      }
    }

    return { isSafe: true, sanitizedQuery: trimmed };
  }

  /**
   * Strict Numerical & Provenance Validator.
   * Cross-references all numerical statistics, currency, kWh, and entity references
   * in the AI response against the authorized backend EnergyContext.
   */
  static validateResponse(
    response: StructuredAIResponse,
    context: EnergyContext
  ): GuardrailValidationResult {
    if (!response || !response.answer) {
      return { isValid: false, rejectionReason: 'Empty response generated by provider.' };
    }

    const text = response.answer;
    const lowerText = text.toLowerCase();

    // 1. Check for fabricated live telemetry claims
    const forbiddenClaims = [
      'we measured in real-time',
      'live meter reading shows',
      'currently consuming',
      'real-time telemetry confirmed',
      'live sensor recorded',
      '99% accuracy guaranteed',
      'exact real-time reading',
    ];

    for (const claim of forbiddenClaims) {
      if (lowerText.includes(claim)) {
        return {
          isValid: false,
          rejectionReason: `Response claimed unsupported real-time telemetry or false accuracy guarantee: "${claim}".`,
        };
      }
    }

    // 2. Check for mentioned appliances not present in user profile
    if (context.appliances.items.length === 0) {
      const specificApplianceKeywords = [
        'your air conditioner',
        'your ac',
        'your washing machine',
        'your deep freezer',
        'your electric cooker',
        'your microwave',
        'your water heater',
      ];
      for (const kw of specificApplianceKeywords) {
        if (lowerText.includes(kw)) {
          return {
            isValid: false,
            rejectionReason: `Response attributed consumption to "${kw}" when user has no registered appliances.`,
          };
        }
      }
    }

    // 3. Hallucination Defense: Validate Currency Amounts (₦ / NGN)
    // Extract all currency figures like ₦10,000 or NGN 5,000 or ₦ 24500
    const currencyMatches = text.match(/(?:₦|NGN\s?)\s?([0-9,]+(?:\.[0-9]{1,2})?)/gi) || [];
    const validCurrencyNumbers = this.collectValidContextNumbers(context);

    for (const rawMatch of currencyMatches) {
      const numericStr = rawMatch.replace(/[^0-9.]/g, '');
      const numVal = parseFloat(numericStr);
      if (!isNaN(numVal) && numVal > 0) {
        // Must match a context spending amount within 2% margin (for rounding differences)
        const isMatched = validCurrencyNumbers.some(
          (valid) => Math.abs(valid - numVal) <= Math.max(1, valid * 0.02)
        );

        if (!isMatched) {
          return {
            isValid: false,
            rejectionReason: `Response hallucinated an unsupported currency amount (${rawMatch}) not found in verified ledger context.`,
          };
        }
      }
    }

    // 4. Hallucination Defense: Validate Unit Claims (kWh)
    // If context has NO valid unit data (unitsKwh is null / 0), reject claims of specific remaining or total units
    const kwhMatches = text.match(/([0-9,]+(?:\.[0-9]{1,2})?)\s?(?:kwh|units)/gi) || [];
    if (context.consumption.totalUnitsKwh === null && context.appliances.totalEstimatedDailyKwh === 0) {
      if (kwhMatches.length > 0) {
        return {
          isValid: false,
          rejectionReason: `Response fabricated specific kWh metrics (${kwhMatches[0]}) when no unit or telemetry data exists in context.`,
        };
      }
    }

    // 5. Ensure response contains honest limitations
    const limitations = response.limitations && response.limitations.length > 0
      ? response.limitations
      : ['Estimates are derived from verified transaction frequency and self-reported profile data.'];

    return {
      isValid: true,
      sanitizedResponse: {
        ...response,
        limitations,
        isGroundTruthGrounded: true,
        dataQualityGrade: context.dataQuality.grade,
      },
    };
  }

  /**
   * Collects all trusted numeric figures from EnergyContext to benchmark against AI claims.
   */
  private static collectValidContextNumbers(context: EnergyContext): number[] {
    const valid: number[] = [];

    if (context.spending) {
      if (context.spending.currentPeriodSpendNaira) valid.push(context.spending.currentPeriodSpendNaira);
      if (context.spending.previousPeriodSpendNaira) valid.push(context.spending.previousPeriodSpendNaira);
      if (context.spending.averageDailySpendNaira) valid.push(context.spending.averageDailySpendNaira);
      if (context.spending.percentageChange) valid.push(Math.abs(context.spending.percentageChange));
    }

    if (context.consumption) {
      if (context.consumption.totalUnitsKwh) valid.push(context.consumption.totalUnitsKwh);
      if (context.consumption.estimatedDailyUnitsKwh) valid.push(context.consumption.estimatedDailyUnitsKwh);
    }

    if (context.purchasing) {
      if (context.purchasing.totalPurchases) valid.push(context.purchasing.totalPurchases);
      if (context.purchasing.medianIntervalDays) valid.push(context.purchasing.medianIntervalDays);
      if (context.purchasing.averageIntervalDays) valid.push(context.purchasing.averageIntervalDays);
    }

    if (context.appliances?.items) {
      context.appliances.items.forEach((a) => {
        if (a.estimatedDailyKwh) valid.push(a.estimatedDailyKwh);
        if (a.estimatedWattage) valid.push(a.estimatedWattage);
        if (a.relativeContributionPct) valid.push(a.relativeContributionPct);
      });
      if (context.appliances.totalEstimatedDailyKwh) valid.push(context.appliances.totalEstimatedDailyKwh);
    }

    if (context.recentPurchases) {
      context.recentPurchases.forEach((p) => {
        if (p.amountNaira) valid.push(p.amountNaira);
        if (p.unitsKwh) valid.push(p.unitsKwh);
      });
    }

    // Common standard calendar numbers
    valid.push(7, 30, 90, 365, 24, 1, 2, 3, 4, 5, 6, 8, 9, 10);

    return valid;
  }

  /**
   * Enforces sliding window rate limits.
   */
  static checkRateLimit(userId: string): { isAllowed: boolean; retryAfterSeconds?: number } {
    const now = Date.now();
    const minuteWindowMs = 60 * 1000;
    const dayWindowMs = 24 * 60 * 60 * 1000;

    let userLimits = this.rateLimitMap.get(userId);
    if (!userLimits) {
      userLimits = {
        minuteCount: 0,
        minuteWindow: now,
        dayCount: 0,
        dayWindow: now,
      };
      this.rateLimitMap.set(userId, userLimits);
    }

    // Reset minute window
    if (now - userLimits.minuteWindow > minuteWindowMs) {
      userLimits.minuteCount = 0;
      userLimits.minuteWindow = now;
    }

    // Reset day window
    if (now - userLimits.dayWindow > dayWindowMs) {
      userLimits.dayCount = 0;
      userLimits.dayWindow = now;
    }

    if (userLimits.minuteCount >= this.RATE_LIMIT_PER_MINUTE) {
      const retryAfter = Math.ceil((userLimits.minuteWindow + minuteWindowMs - now) / 1000);
      return { isAllowed: false, retryAfterSeconds: Math.max(1, retryAfter) };
    }

    if (userLimits.dayCount >= this.RATE_LIMIT_PER_DAY) {
      const retryAfter = Math.ceil((userLimits.dayWindow + dayWindowMs - now) / 1000);
      return { isAllowed: false, retryAfterSeconds: Math.max(1, retryAfter) };
    }

    userLimits.minuteCount++;
    userLimits.dayCount++;

    return { isAllowed: true };
  }

  /**
   * Retrieves cached response if present and valid.
   */
  static getCachedResponse(
    userId: string,
    meterId: string | null,
    period: string,
    question: string
  ): StructuredAIResponse | null {
    const key = this.buildCacheKey(userId, meterId, period, question);
    const cached = this.responseCache.get(key);
    if (cached && cached.expiresAt > Date.now()) {
      return cached.response;
    }
    return null;
  }

  /**
   * Stores response in scoped cache (5-minute TTL).
   */
  static setCachedResponse(
    userId: string,
    meterId: string | null,
    period: string,
    question: string,
    response: StructuredAIResponse,
    ttlSeconds = AI_CONFIG.guardrails.cacheTtlSeconds
  ): void {
    const key = this.buildCacheKey(userId, meterId, period, question);
    this.responseCache.set(key, {
      response,
      expiresAt: Date.now() + ttlSeconds * 1000,
    });
  }

  /**
   * Strict validation of AI-calculated structured analytics against mechanical ground truth.
   */
  static validateAnalytics(
    analytics: StructuredInsightsAnalytics,
    context: EnergyContext
  ): AnalyticsValidationResult {
    if (!analytics) {
      return { isValid: false, rejectionReason: 'Empty analytics payload returned by provider.' };
    }

    // 1. Validate Purchase Frequency: Must match qualifying transaction count in context
    if (
      analytics.purchaseFrequency?.value !== null &&
      analytics.purchaseFrequency?.value !== undefined
    ) {
      const expectedCount = context.purchasing.totalPurchases;
      if (analytics.purchaseFrequency.value !== expectedCount) {
        return {
          isValid: false,
          rejectionReason: `AI purchase frequency (${analytics.purchaseFrequency.value}) diverges from authoritative source count (${expectedCount}).`,
        };
      }
    }

    // 2. Validate Spend Numbers: Must not be negative or NaN
    if (analytics.periodSpend?.value !== null && analytics.periodSpend?.value !== undefined) {
      if (isNaN(analytics.periodSpend.value) || analytics.periodSpend.value < 0) {
        return { isValid: false, rejectionReason: 'Period spend is negative or invalid NaN.' };
      }
      // Mechanically check spend against context current spend
      if (Math.abs(analytics.periodSpend.value - context.spending.currentPeriodSpendNaira) > 5) {
        return {
          isValid: false,
          rejectionReason: `Period spend (₦${analytics.periodSpend.value}) does not match source records (₦${context.spending.currentPeriodSpendNaira}).`,
        };
      }
    }

    // 3. Validate Days Remaining: Must not be negative or Infinity
    if (analytics.estimatedDaysRemaining?.value !== null && analytics.estimatedDaysRemaining?.value !== undefined) {
      if (
        isNaN(analytics.estimatedDaysRemaining.value) ||
        !isFinite(analytics.estimatedDaysRemaining.value) ||
        analytics.estimatedDaysRemaining.value < 0
      ) {
        return { isValid: false, rejectionReason: 'Estimated days remaining contains invalid or infinite value.' };
      }
    }

    // 4. Validate Cadence: Require >= 2 purchases for numeric interval
    if (context.purchasing.totalPurchases <= 1 && analytics.purchaseCadence?.value !== null) {
      return {
        isValid: false,
        rejectionReason: 'Cadence interval must be null when purchase count is <= 1.',
      };
    }

    return { isValid: true, sanitizedAnalytics: analytics };
  }

  /**
   * Retrieves cached analytics if present and valid.
   */
  static getCachedAnalytics(
    userId: string,
    meterId: string | null,
    period: string
  ): StructuredInsightsAnalytics | null {
    const key = `${userId}:${meterId || 'all'}:${period}`;
    const cached = this.analyticsCache.get(key);
    if (cached && cached.expiresAt > Date.now()) {
      return cached.analytics;
    }
    return null;
  }

  /**
   * Stores analytics in scoped cache.
   */
  static setCachedAnalytics(
    userId: string,
    meterId: string | null,
    period: string,
    analytics: StructuredInsightsAnalytics,
    ttlSeconds = AI_CONFIG.guardrails.cacheTtlSeconds
  ): void {
    const key = `${userId}:${meterId || 'all'}:${period}`;
    this.analyticsCache.set(key, {
      analytics,
      expiresAt: Date.now() + ttlSeconds * 1000,
    });
  }

  /**
   * Invalidates cached responses and analytics for a user (e.g. after a purchase).
   */
  static invalidateUserCache(userId: string): void {
    for (const key of this.responseCache.keys()) {
      if (key.startsWith(`${userId}:`)) {
        this.responseCache.delete(key);
      }
    }
    for (const key of this.analyticsCache.keys()) {
      if (key.startsWith(`${userId}:`)) {
        this.analyticsCache.delete(key);
      }
    }
  }

  private static buildCacheKey(
    userId: string,
    meterId: string | null,
    period: string,
    question: string
  ): string {
    const cleanQ = question.toLowerCase().trim().replace(/[^a-z0-9]/g, '');
    return `${userId}:${meterId || 'all'}:${period}:${cleanQ}`;
  }
}
